apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-namespace.yaml
  - argocd-install.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: soc-platform
